export { ConstantFoldingStep } from "./constant-folding.js";
export { DeadCodeEliminationStep } from "./dead-code-elimination.js";
export { CommonSubexpressionEliminationStep } from "./common-subexpression-elimination.js";
export { ConstantPropagationStep } from "./constant-propagation.js";
export { JumpOptimizationStep } from "./jump-optimization.js";
export { BlockMergingStep } from "./block-merging.js";
export { ReturnMergingStep } from "./return-merging.js";
export { ReadWriteMergingStep } from "./read-write-merging.js";
export { TailCallOptimizationStep } from "./tail-call-optimization.js";
